name: Daily Flight Watcher
on:
  schedule:
    - cron: "5 13 * * *"   # runs daily at 13:05 UTC
  workflow_dispatch: {}     # lets you run it manually
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Verify code on runner
        run: |
          echo "Commit: $GITHUB_SHA"
          echo "Looking for old fromisoformat call…"
          grep -n 'fromisoformat(route\["start_date"\])' main.py || echo "Not found"
          echo "---- main.py (first 220 lines, numbered) ----"
          nl -ba main.py | sed -n '1,220p'
      - name: Verify code on runner
        run: |
          echo "Commit SHA: $GITHUB_SHA"
          echo "--- Repo root listing ---"
          ls -la
          echo "--- Search for old fromisoformat call ---"
          grep -n 'fromisoformat(route\["start_date"\])' main.py || echo "Not found"
          echo "--- First 220 lines of main.py (numbered) ---"
          nl -ba main.py | sed -n '1,220p'

      - name: Run watcher
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python main.py
